[pytest]
addopts = -v --html=reports/report.html --self-contained-html --reruns=1 --reruns-delay=2
testpaths = tests

; pytest -m "markers" for running specific tests with markers
; Example: pytest -m "smoke" for running smoke tests

markers =
    smoke: smoke tests
    regression: regression tests
    auth: authentication module tests
    dashboard: dashboard module tests
    pim: pim module tests
    leave: leave module tests
    admin: admin module tests
    my_info: my info module tests
    time: time module tests
    recruitment: recruitment module tests
    performance: performance module tests
    directory: directory module tests
    maintenance: maintenance module tests
    claim: claim module tests
    buzz: buzz module tests
    e2e: end-to-end tests