base_url: "https://opensource-demo.orangehrmlive.com"
browser: "chrome"
# headless: false
headless: true
timeouts:
  explicit_wait_seconds: 15
credentials:
  username_env: "ORANGEHRM_USERNAME"
  password_env: "ORANGEHRM_PASSWORD"
artifacts:
  screenshots_dir: "reports/screenshots"